#!/bin/bash

#DEFAULT_START_OPTS='-use-control-port -nofork -nobrowser -verbose'

#cd /opt/aem && exec java $CQ_JVM_OPTS -jar AEM_6.4_Quickstart.jar $DEFAULT_START_OPTS "$@"

DEFAULT_START_OPTS='-use-control-port -nofork -nobrowser -verbose'
# -Xdebug -Xrunjdwp:transport=dt_socket,address=30303,server=y,suspend=n'

cd /opt/aem && exec java $CQ_JVM_OPTS -jar AEM_6.4_Quickstart.jar $DEFAULT_START_OPTS "$@"
#cd /opt/aem && exec java $CQ_JVM_OPTS -jar crx-quickstart/app/cq-quickstart-6.4.0-standalone-quickstart.jar  $DEFAULT_START_OPTS "$@"
#cd /opt/aem && exec java $CQ_JVM_OPTS  -jar crx-quickstart/app/cq-quickstart-6.4.0-standalone-quickstart.jar start  $DEFAULT_START_OPTS "$@"

#-Djava.locale.providers=CLDR,JRE,SPI -c crx-quickstart -i launchpad  -Dsling.properties=conf/sling.properties
